adds bank account tracking adapter to retrieve bank account tracking record
craftgate/craftgate-go-client pull request #41
Opened 2023-07-24 12:36 UTC by AlicanAkkus

2023-08-01 06:32 UTC, lemiorhan approved these changes

2023-10-06 07:53 UTC, reywyn requested changes

2023-10-06 07:53 UTC, reywyn commented on adapter/model.go
> +	RECEIVE Currency   = "RECEIVE"
RecordType_Send
RecordType_Receive

2023-10-06 07:53 UTC, reywyn commented on adapter/model.go
> +	YKB BankAccountTrackingSource = "YKB"
BankAccountTrackingSource_YKB

2023-10-06 07:53 UTC, reywyn commented on tests/bank_account_tracking_test.go
> +		Currency: craftgate.Currency("TRY"),
`.Currency_TRY` olmuyor muydu

2023-11-10 09:03 UTC, merged